name: CI-CD
on:
  push:
    branches: ["main","develop","release/**"]
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_artifact_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

