name: CI-CD
on:
  push:
    branches: ["main","develop","release/**"]
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_cloud_function:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Quality Checks
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.PROJECT_ID }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ENVIRONMENT: "TEST"
        run: |
          coverage run -m pytest
          coverage report --fail-under=99

      - name: Lint code
        run: pip install flake8 && flake8 src/

      - name: Upload coverage results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .
          if-no-files-found: error
          retention-days: 10

